#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)/.."
DEPLOY_DIR="/app/cryobs.xyz"
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "Deploy..."

while read oldrev newrev refname; do
  echo "Received push to $refname, deploying commit $newrev..."

  git --work-tree="$TEMP_DIR" --git-dir="$REPO_DIR" checkout -f "$newrev"
  echo "Checked out commit $newrev into $TEMP_DIR"

  cd $TEMP_DIR
  ./cicd/deploy.sh "$DEPLOY_DIR"
done

