#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)/.."

while read oldrev newrev refname; do
  echo "Received push to $refname..."
  echo "New revision: $newrev"

  TEMP_DIR=$(mktemp -d)
  trap 'rm -rf "$TEMP_DIR"' EXIT

  git --git-dir="$REPO_DIR" archive "$newrev" | tar -x -C "$TEMP_DIR"
  echo "Archive $newrev into $TEMP_DIR"

  cd "$TEMP_DIR"
  ./cicd/test.sh
done

