#!/bin/bash
set -e 

REPO_DIR=""
TMP_DIR=${mktemp -d}

echo "Running pre-receive checks..."

# read all branches
while read oldrev newrev refname; do 
  echo "Checking branch: $refname"

  # checkout new version to temp directory
  git --work-tree="$TMP_DIR" --git-dir="$REPO_DIR" \
    checkout -f "$newrev" >/dev/null 2>&1 
  cd "$TMP_DIR"

  # check if build exists
  if [ -x "./cicd/build.sh" ]; then
    if ! ./cicd/build.sh; then
      echo "Build failed for $refname"
      rm -rf "$TMP_DIR"
      exit 1
    fi
  fi

    

  # check if tests exists
  if [ -x "./cicd/tests.sh" ]; then
    echo "Testing..."
    if ! ./cicd/tests.sh; then
      echo "Tests failed for $refname"
      rm -rf "$TMP_DIR"
      exit 1
    fi
  fi

  echo "CI succeeded for $refname"
done

rm -rf "$TMP_DIR"
exit 0

